# Python Fundamentals
#### by: Chenshu Liu

## Table of contents
1. [Introduction](#Introduction)
2. [List](##List)
    1. [Sorting List](#Sorting-List)
    2. [List Creation](#List-Creating)
    3. [List Manipulation](#List-Manipulation)
    4. [List Copying](#List-Copying)
    5. [Copy Without Simultaneous Change](#Copy-Without-Simultaneous-Change)
    6. [List Comprehension](#List-Comprehension)
3. [Tuple](#Tuple)
    1. [Tuple Definition](#Tuple-Definition)
    2. [Tuple Extraction](#Tuple-Extraction)
    3. [Tuple Methods](#Tuple-Methods)
    4. [List and Tuple Conversion](#List-and-Tuple-Conversion)
    5. [Tuple Slicing](#Tuple-Slicing)
    5. [Unpacking](#Unpacking)
    6. [List vs. Tuple](#List-vs.-Tuple)
4. [Dictionary](#Dictionary)
    1. [Dictionary Manipulation](#Dictionary-Manipulation)
    2. [Checking Element](#Checking-Element)
    3. [Copying Dictionary](#Copying-Dictionary)
    4. [Merging](#Merging)
5. [Set](#Set)
    1. [Creating & Modifying Sets](#Creating-&-Modifying-Sets)
    2. [Merging Sets](#Merging-Sets)
    3. [Inter-sets Operations](#Inter-sets-Operations)
    4. [Frozen Set](#Frozen-Set)
6. [Strings](#Strings)
    1. [String Definition](#String-Definition)
    2. [String Indexing](#String-Indexing)
    3. [String Detection](#String-Detection)
    4. [String Manipulation](#String-Manipulation)
    5. [String Formatting](#String-Formatting)
7. [Itertools](#Itertools)
    1. [Product](#Product)
    2. [Permutation](#Permutation)
    3. [Combination](#Combination)
    4. [Accumulate](#Accumulate)
8. [Lambda Functions](#Lambda-Functions)
    1. [Lambda Function](#Lambda-Function)
    2. [Map Function](#Map-Function)
9. [Exceptions and Errors](#Exceptions-and-Errors)
    1. [Raise Exception](#Raise-Exception)
    2. [Assertion](#Assertion)
    3. [Try-exception](#Try-exception)
    4. [Define Own Exception](#Define-Own-Exception)

## Introduction
This Python tutorial has the following attributed links:
* https://www.youtube.com/watch?v=HGOBQPFzWKo&t=1419s
* https://www.earthdatascience.org/courses/intro-to-earth-data-science/file-formats/use-text-files/format-text-with-markdown-jupyter-notebook/

## List
* Lists are ordered, mutable, and allow for duplicate elements

### Sorting List

In [1]:
# sort list **in place** (changing the original list)
list1 = [4, 3, 1, -1 -5, 10]
print(list1)
new_list1 = list1.sort()
print(list1)
print(new_list1)

# sort and assign to new object
list2 = [4, 3, 1, -1 -5, 10]
print(list2)
new_list2 = sorted(list2)
print(list2)
print(new_list2)

[4, 3, 1, -6, 10]
[-6, 1, 3, 4, 10]
None
[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[-6, 1, 3, 4, 10]


### List Creation

In [1]:
# creating repeating elements in a list
list1 = [0] * 5
print(list1)

list2 = [1, 2, 3] * 5
print(list2)

# list concatenation
list3 = list1 + list2
print(list3)

# create a list from 1 to 10
list4 = list(range(1, 11))
print(list4)

[0, 0, 0, 0, 0]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[0, 0, 0, 0, 0, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


### List Manipulation

In [3]:
# slicing
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# select all
a = list1[:]
print(a)

# select by start and end
b = list1[1:5]
print(b)

# select only with start
c = list1[1:]
print(c)

# step
d = list1[::2] # select every two steps (every other one)
print(d)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5]
[2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


### List Copying
When copying two list, when the first list (the one being copied) is modified, the second list (the one that was copied to) will also be modified

In [4]:
list1 = [4, 3, 1, -1 -5, 10]
list2 = list1
print(f"the original list1 is {list1}")
print(f"the original list2 is {list2}")

# modify list1 by sorting
list1.sort()

# both list1 and list2 changes
print(f"list1 after modification is {list1}")
print(f"list2 after modification is {list2}")

# problem with pointers
test = [0, 0, 0, 0, 0]
b = []
for i in range(len(test)):
    # change pointer
    test = test.copy()
    test[i] = test[i] + 1
    b.append(test)
    print(b)

[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[-6, 1, 3, 4, 10]
[-6, 1, 3, 4, 10]


### Copy Without Simultaneous Change

In [5]:
list1 = [4, 3, 1, -1 -5, 10]

# copy by copy() method
list2 = list1.copy()

# copy by list function
list3 = list(list1)

# copy by list selection
list4 = list1[:]

print(list1)
print(list2)
print(list3)
print(list4)

# modify list1 by sorting
list1.sort()

print(list1)
print(list2)
print(list3)
print(list4)

[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[-6, 1, 3, 4, 10]
[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]
[4, 3, 1, -6, 10]


### List Comprehension

In [7]:
a = [1, 2, 3, 4, 5, 6]
# syntax: [expression for iterator in list]
b = [i*i for i in a]
print(a)
print(b)

[1, 2, 3, 4, 5, 6]
[1, 4, 9, 16, 25, 36]


## Tuple
* Tuple is ordered, **inmmutable**, and allows duplicated elements

### Tuple Definition

In [14]:
mytuple = ("Max", "28", "Boston")
print(mytuple)

# need comma to define a single element tuple
tuple1 = ("Max")
print(type(tuple1))
tuple2 = ("Max",)
print(type(tuple2))

# tuple can also be created using the tuple function
tuple3 = tuple(["Max", 28, "Boston"])
print(tuple3)
print(type(tuple3))

('Max', '28', 'Boston')
<class 'str'>
<class 'tuple'>
('Max', 28, 'Boston')
<class 'int'>
<class 'str'>
<class 'tuple'>


### Tuple Extraction

In [15]:
tuple1 = tuple(["Max", 28, "Boston"])
element1 = tuple1[1]
print(element1)
print(type(element1))

element2 = tuple1[2]
print(element2)
print(type(element2))

element3 = tuple1[-2]
print(element3)
print(type(element3))

28
<class 'int'>
Boston
<class 'str'>
28
<class 'int'>


In [16]:
if "Max" in tuple1:
    print("Yes")

Yes


### Tuple Methods

In [20]:
# counting number of occurrences of each element
tuple1 = ("a", "p", "p", "l", "e")
print(tuple1.count("a"))
print(tuple1.count("p"))
print(tuple1.count("o"))

# find the index of the first occurrence
print(tuple1.index("a"))
print(tuple1.index("p"))
# print(tuple1.index("o")) will give an error

1
2
0
0
1


### List and Tuple Conversion

In [21]:
# tuple convert to list
tuple1 = ("a", "p", "p", "l", "e")
print(type(tuple1))
list1 = list(tuple1)
print(type(list1))

# list convert to tuple
list2 = ["a", "p", "p", "l", "e"]
print(type(list2))
tuple2 = tuple(list2)
print(type(tuple2))

<class 'tuple'>
<class 'list'>
<class 'list'>
<class 'tuple'>


### Tuple Slicing

In [25]:
a = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(a)
b = a[2:5]
print(b)

# selection with stepping
c = a[::2]
print(c)

# negative stepping (reverse)
d = a[::-1]
print(d)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
(3, 4, 5)
(1, 3, 5, 7, 9)
(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)


### Unpacking

In [30]:
tuple1 = ("Max", 28, "Boston")
# correspond with tuple elements (must have exact match 3-3)
name, age, city = tuple1
print(name)
print(age)
print(city)

tuple2 = (0, 1, 2, 3, 4)
i1, *i2, i3 = tuple2
print(i1)
print(i2) # anything in between i1 and i3
print(i3)

Max
28
Boston
0
[1, 2, 3]
4


### List vs. Tuple
Both list and tuple are able to store elements, there are some key differences:
* Tuple are immutable, meaning we cannot change the elements inside either by adding or dropping
* Tuple takes up less memory space than list, even if they are storing the same elements

In [31]:
import sys
my_list = [0, 1, 2, "hello", True]
my_tuple = (0, 1, 2, "hello", True)
print(sys.getsizeof(my_list), "bytes")
print(sys.getsizeof(my_tuple), "bytes")

96 bytes
80 bytes


## Dictionary
* Dictionary is key-value pairs, unsorted, and mutable
* Tuple can be used a key for dictionary because it is inmutable
* List **cannot** be used as key for dictionary because it is mutable

In [20]:
# creating dictionary using {}
mydict = {"name":"Max", "age": 28, "city": "New York"}
print(mydict)

# creating dictionary using dict() function
# don't need to use quotes for the keys
mydict2 = dict(name = "Max", age = 28, city = "New York")
print(mydict2)

# calling elements directly by key
value = mydict["name"]
print(value)

# obtain keys and values
print(mydict.values())
print(mydict.keys())
print(mydict.items())

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York'}
Max
dict_values(['Max', 28, 'New York'])
dict_keys(['name', 'age', 'city'])
dict_items([('name', 'Max'), ('age', 28), ('city', 'New York')])


### Dictionary Manipulation

In [6]:
# adding new item to dictionary
mydict = {"name":"Max", "age": 28, "city": "New York"}
mydict["email"] = "Max000@gmail.com"
print(mydict)

# deleting element from dictionary
del mydict["email"]
print(mydict)

# OR use the pop method
mydict.pop("age")
print(mydict)

{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'Max000@gmail.com'}
{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'city': 'New York'}


### Checking Element

In [19]:
# check by if statement
if "name" in mydict:
    print(mydict["name"])

# check by try and except method
try:
    print(mydict["lastname"])
except:
    print("Error")
    
# looping
for value in mydict:
    print(value)
    
for value in mydict.values():
    print(value)
    
for key in mydict:
    print(key)

for key in mydict.keys():
    print(key)
    
for key, value in mydict.items():
    print(key, value)

Max
Error
name
age
city
Max
28
New York
name
age
city
name
age
city
name Max
age 28
city New York


### Copying Dictionary
* Copying dictionary directly by assigning the original and modifying either one will lead to change in the other
* Use the `copy()` method will prevent simultaneous change

In [23]:
# simultaneous change
mydict1 = {"name":"Max", "age":28, "city":"New York"}
mydict_cpy1 = mydict1
print(mydict1)
print(mydict_cpy1)
mydict_cpy1["email"] = "abc@def.com"
print(mydict_cpy1)
print(mydict1)

# independent
mydict2 = {"name":"Max", "age":28, "city":"New York"}
mydict_cpy2 = mydict2.copy()
print(mydict2)
print(mydict_cpy2)
mydict_cpy2["email"] = "abc@def.com"
print(mydict_cpy2)
print(mydict2)

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'abc@def.com'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'abc@def.com'}
{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'abc@def.com'}
{'name': 'Max', 'age': 28, 'city': 'New York'}


### Merging

In [27]:
# overwriting merge
mydict1 = {"name": "Max", "age": 28, "email": "abc@def.com"}
mydict2 = dict(name = "Mary", age = 27, city = "New York")
print(mydict1)
print(mydict2)
mydict1.update(mydict2)
print(mydict1)

{'name': 'Max', 'age': 28, 'email': 'abc@def.com'}
{'name': 'Mary', 'age': 27, 'city': 'New York'}
{'name': 'Mary', 'age': 27, 'email': 'abc@def.com', 'city': 'New York'}


## Set

Set is unordered, mutable, and does not allow duplicates

Sets can be defined using`{}`, same as dictionaries, but it does not require key - value pairs

### Creating & Modifying Sets

In [8]:
myset = {1, 2, 3}
myset1 = {1, 2, 3, 2, 1}
myset2 = set([1, 2, 3])
myset3 = set("Hello")
print(myset)
print(myset1)
print(myset2)
# note that letter "l" will only be printed once because set does not allow duplicates
print(myset3)

# define empty set
emptyset = {}
print(type(emptyset))
# note that the type of emptyset is still dictionary
# to define an empty set, we must use the set function
emptyset1 = set()
print(type(emptyset1))

# add elements to empty set
emptyset1.add(1)
emptyset1.add(2)
emptyset1.add(3)
print(emptyset1)

# remove elements from set (remove method)
emptyset1.remove(3)
print(emptyset1)
# remove elements from set (discard method)
# discard method will not raise error when key index is wrong
emptyset1.discard(4) # no error like remove method
print(emptyset1)

{1, 2, 3}
{1, 2, 3}
{1, 2, 3}
{'l', 'e', 'H', 'o'}
<class 'dict'>
<class 'set'>
{1, 2, 3}
{1, 2}
{1, 2}


### Inter-sets Operations
We can find the union, intersection, difference between sets

In [9]:
odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
primes = {2, 3, 5, 7}
print(odds)
print(evens)
print(primes)

# union (merging without duplicates)
u = odds.union(evens)
print(u)

# intersection
i = odds.intersection(evens)
print(i) # empty set b/c odds and evens do not have same element(s)

setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
# get numbers in setA but not in setB
diff = setA.difference(setB)
print(diff)
# get numbers in setB but not in setA
diff2 = setB.difference(setA)
print(diff2)
# get numbers that are not in both sets
diff3 = setB.symmetric_difference(setA)
print(diff3)

# in place modification
setA.update(setB)
# update the original setA by adding elements that only exist in setB
print(setA)
# keeping only the elements in the intersection in place
setA.intersection_update(setB)
print(setA)
# keeping only the difference between the two sets in place
setA.difference_update(setB)
print(setA)

setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3}
setC = {10}
print(setA.issubset(setB))
print(setA.issuperset(setB))
print(setA.isdisjoint(setB))
print(setB.isdisjoint(setC))

{1, 3, 5, 7, 9}
{0, 2, 4, 6, 8}
{2, 3, 5, 7}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
set()
{4, 5, 6, 7, 8, 9}
{10, 11, 12}
{4, 5, 6, 7, 8, 9, 10, 11, 12}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{1, 2, 3, 10, 11, 12}
set()
False
True
False
True


### Frozen Set
The elements within a frozen set cannot be changed or modified

In [12]:
a = frozenset([1, 2, 3, 4])
print(a)

# if tried to modify elements within, will receive error
# a.remove(2)

frozenset({1, 2, 3, 4})


## Strings
Strings are ordered, immutable, text representations
<br/>String objects do not support item assignment

### String Definition

In [30]:
my_string = "Hello World"
print(my_string)

# quote recursion in string definition
# need to use alternating double/single quotes
my_string = "I'm a programmer"
print(my_string)
# or use escape sign '\'
my_string = 'I\'m a programmer'
print(my_string)

# multiline string can be definied through triple quotes
my_string = """First line
Second line
Third line"""
print(my_string)

# string concatenation
greeting = "Hello"
name = "Tom"
sentence = greeting + " " + name
print(sentence)

# cleaning strings with white spaces
my_string = "     Hello World     "
print(my_string)
my_string = my_string.strip()
print(my_string)

# converting all characters to upper/lowercase
print(my_string)
print(my_string.upper())
print(my_string.lower())

Hello World
I'm a programmer
I'm a programmer
First line
Second line
Third line
Hello Tom
     Hello World     
Hello World
Hello World
HELLO WORLD
hello world


### String Indexing

In [2]:
my_string = "Hello World"
# the first character in the string
char = my_string[0]
print(char)
# the last character in the string through negative indexing
char = my_string[-1]
print(char)

# string objects do not support item assignment
# assigning new item to a position through indexing will generate error
# my_string[0] = 'h'

# slicing
# the start index is inclusive, the stop index is exclusive
substring = my_string[1:5]
print(substring)
# slicing with step 2
substring1 = my_string[::2]
print(substring1)
# slicing with negative step = reversing
substring2 = my_string[::-1]
print(substring2)

# iteration
greeting = "Hello"
for i in greeting:
    print(i)

H
d
ello
HloWrd
dlroW olleH
H
e
l
l
o
4
-1
2
Hello Universe


### String Detection

In [3]:
greeting = "Hello"
# finding position of character
print(greeting.find("o"))
# if does not find a match, will return -1
print(greeting.find("lol"))
# find the number of matching characters
print(greeting.count("l"))
# find and replace matching string
my_string = "Hello World"
print(my_string.replace("World", "Universe"))

4
-1
2
Hello Universe


### String Manipulation

In [10]:
my_string = "how are you doing"
print(my_string)
# split the string into individual strings by word
# default separator is space " "
my_list = my_string.split()
print(my_list)
# concatenate strings to one
new_string = "_".join(my_list)
print(new_string)

my_list = ["a"] * 6
print(my_list)
my_string = "" # empty string
for i in my_list:
    my_string += i # BAD CODE!
    # string is immutable, which will create a new string each iteration
    # takes a lot of memory
print(my_string)

how are you doing
['how', 'are', 'you', 'doing']
how_are_you_doing
['a', 'a', 'a', 'a', 'a', 'a']
aaaaaa


### String Formatting

In [18]:
var = "Tom"
# %s means that is a place holder for a string
my_string = "the variable is %s" % var
print(my_string)

var = 3
# %d is a place holder for decimal value
my_string = "the variable is %d" % var
print(my_string)

var = 3.1415926
# %f is a place holder for floating point value (default 6 digits)
# .2 before the f means we only want to display 2 digits after the decimal point
my_string = "the variable is %.2f" % var
print(my_string)

# .format method
var = 3.1415926
my_string = "the variable is {}".format(var)
print(my_string)
my_string = "the variable is {:.2f}".format(var)
print(my_string)
# for multiple variables
var2 = 6
my_string = "the variable is {} and {}".format(var, var2)
print(my_string)

# f-strings method
var = 3.1415926
var2 = 6
my_string = f"the variable is {var} and {var2*2}"
print(my_string)

the variable is Tom
the variable is 3
the variable is 3.14
the variable is 3.1415926
the variable is 3.14
the variable is 3.1415926 and 6
the variable is 3.1415926 and 12


## Itertools

### Product

In [19]:
from itertools import product
a = [1, 2]
b = [3, 4]
prod = product(a, b)
print(list(prod)) # the cartesian product

[(1, 3), (1, 4), (2, 3), (2, 4)]


### Permutation

In [20]:
from itertools import permutations
# return all possible orderings
a = [1, 2, 3]
perm = permutations(a, 2)
# 2 is the length of the permutated arrays
print(list(perm))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


### Combination

In [23]:
from itertools import combinations, combinations_with_replacement
a = [1, 2, 3, 4]
comb = combinations(a, 2)
print(list(comb))

# allow case of combining with itself (e.g. (1, 1))
comb = combinations_with_replacement(a, 2)
print(list(comb))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


### Accumulate

In [29]:
from itertools import accumulate
import operator
a = [1, 2, 3, 4]
acc = accumulate(a)
print(a)
print(list(acc))

acc2 = accumulate(a, func = operator.mul)
print(a)
print(list(acc2))

a = [1, 2, 5, 3, 4]
acc3 = accumulate(a, func = max)
print(a)
# this will return max with stepwise comparison
print(list(acc3))

[1, 2, 3, 4]
[1, 3, 6, 10]
[1, 2, 3, 4]
[1, 2, 6, 24]
[1, 2, 5, 3, 4]
[1, 2, 5, 5, 5]


## Lambda Functions
Small, one-line function that is for easy operations

### Lambda Function

In [36]:
# syntax:
# lambda arguments: expression
add10 = lambda x: x + 10
# the variable is the function
print(add10(5))

mult = lambda x, y: x*y
print(mult(2, 3))

# lambda functions are short, usually the helper function of other operations
points2D = [(1, 2), (15, 1), (5, -1), (10, 4)]
print(points2D)
points2D_sortx = sorted(points2D) # default sort according to first value
print(points2D_sortx)
# sort according to the second value of the tuples
points2D_sorty = sorted(points2D, key = lambda x: x[1])
print(points2D_sorty)

15
6
[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]
[(5, -1), (15, 1), (1, 2), (10, 4)]


### Map Function

In [46]:
a = [1, 2, 3, 4, 5]
# similar to the vectorization in R
# map applies operation to each element in the list
b = map(lambda x: x*2, a)
print(a)
print(list(b))

[1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


### Filter Function

In [48]:
a = list(range(1, 7))
# select all the even numbers
b = filter(lambda x: x%2 == 0, a)
print(list(b))

# achieve the same thing using list comprehension
c = [x for x in a if x%2 == 0]
print(c)

[2, 4, 6]
[2, 4, 6]


## Exceptions and Errors

Different types of errors include:
* Name error
* Syntax error
* Type error
* Module error (does not have the library specified)
* File error (does not have the file indicated)
* Index error (when indexing with invalid index)

### Raise Exception

In [8]:
# how to raise an exception
x = -5
if x < 0:
    raise Exception("x should be positive")

Exception: x should be positive

### Assertion

In [11]:
# use assertion to raise exception
# this will raise an assertion error
x = -5
assert (x >= 0), 'x is not positive'

AssertionError: x is not positive

### Try-exception

In [12]:
try:
    a = 5/0
except:
    print("an error occurred")

an error occurred


In [13]:
try:
    a = 5/0
except Exception as e:
    # print the exception message
    print(e)

division by zero


### Define Own Exception

In [17]:
class ValueTooHighError(Exception):
    pass

class ValueTooSmallError(Exception):
    def __init__(self, message, value):
        self.message = message
        self.value = value

def test_value(x):
    if x > 100:
        raise ValueTooHighError("value is too high")
    if x < 5:
        raise ValueTooSmallError("value is too small", x)

try:
    test_value(1)
except ValueTooHighError as e:
    print(e)
except ValueTooSmallError as e:
    print(e.message, e.value)

value is too small 1


## Random Numbers

### The random Package

In [33]:
# pseudorandom
import random

a = random.random()
print(a)

# randomly from uniform distribution
a = random.uniform(1, 10)
print(a)

# random integers
# inclusive upper-bound
a = random.randint(1, 10)
print(a)

# exclusive upper-bound
# does not include 10
a = random.randrange(1, 10)
print(a)

# select random elements
mylist = list("ABCDEFGH")
a = random.choices(mylist, k = 3)
print(a)

# random shuffle
# in-place shuffling
mylist = list("ABCDEFGH")
print(mylist)
random.shuffle(mylist)
print(mylist)

# reproducible randomness
# setting the seed to reproduce the random sampling
random.seed(123)
print(random.random())
print(random.randint(1, 10))
random.seed(123)
print(random.random())
print(random.randint(1, 10))

0.7689563885870707
3.398984312782452
1
7
['E', 'C', 'G']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['G', 'A', 'D', 'F', 'E', 'H', 'B', 'C']
0.052363598850944326
2
0.052363598850944326
2
[0.39211752 0.34317802 0.72904971]
[4 5 1 1]
[[5 2 8 4]
 [3 5 8 3]
 [5 9 1 8]]
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]


### The Numpy Library

In [ ]:
# random number generation using Numpy
import numpy as np
a = np.random.rand(3)
print(a)
# the upperbound is exclusive
b = np.random.randint(1, 10, 4)
print(b)
c = np.random.randint(1, 10, (3, 4))
print(c)

# setting seed using numpy
np.random.seed(123)
# randomly choose 3 * 3 array
print(np.random.rand(3, 3))
np.random.seed(123)
print(np.random.rand(3, 3))